# Generated by Django 2.2.1 on 2019-05-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='register_4',
            field=models.BooleanField(default=False, verbose_name='Четверг'),
        ),
        migrations.AlterField(
            model_name='player',
            name='register_6',
            field=models.BooleanField(default=False, verbose_name='Суббота'),
        ),
    ]
