# Generated by Django 2.2.1 on 2019-05-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_player_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='registered',
            field=models.BooleanField(default=False, verbose_name='Зарегестрирован'),
        ),
    ]
