# Generated by Django 2.2.1 on 2019-05-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20190515_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата'),
        ),
    ]
