# Generated by Django 2.2.1 on 2019-05-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_player_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='registered',
            field=models.BooleanField(default=False, verbose_name='ОК'),
        ),
    ]
