# Generated by Django 2.2.1 on 2019-05-15 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20190516_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='register_4',
        ),
        migrations.RemoveField(
            model_name='player',
            name='register_6',
        ),
    ]
