# Generated by Django 2.2.1 on 2019-05-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20190516_0202'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('players', models.CharField(blank=True, editable=False, max_length=256, verbose_name='Players')),
            ],
            options={
                'verbose_name': 'Register task',
                'verbose_name_plural': 'Register_tasks',
            },
        ),
        migrations.RemoveField(
            model_name='player',
            name='date',
        ),
    ]
