# Generated by Django 2.2.1 on 2019-05-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20190522_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='registertask',
            name='activation_time',
            field=models.DateTimeField(null=True, verbose_name='Init time'),
        ),
    ]
