# Generated by Django 2.2.1 on 2019-05-16 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vkapi_wrapper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='key',
            old_name='key',
            new_name='value',
        ),
    ]
