# Generated by Django 2.2.1 on 2019-05-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkapi_wrapper', '0002_auto_20190516_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=64, verbose_name='App ID')),
                ('access_token', models.CharField(max_length=256, verbose_name='Access key')),
                ('group_id', models.CharField(max_length=64, verbose_name='Group id')),
            ],
            options={
                'verbose_name': 'Ключи',
                'verbose_name_plural': 'Ключи',
            },
        ),
        migrations.DeleteModel(
            name='Key',
        ),
    ]
