# Generated by Django 2.2.1 on 2019-05-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkapi_wrapper', '0003_auto_20190516_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='keys',
            name='name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Title'),
        ),
    ]
