# Generated by Django 2.2.1 on 2019-05-17 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vkapi_wrapper', '0004_keys_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keys',
            old_name='name',
            new_name='title',
        ),
    ]
